/**
 * @file Lab9_ek0772.cpp
 * @date 2026-04-12
 * @author Elijah K
 * @brief Demonstrates inheritance and poymorphism in C++.
 * Starter code: Account.h, Account.cpp, Customer.h, Customer.cpp, Source.cpp, written by Anderson Wood.
 * Source.cpp renamed to Lab9_ek0772.cpp, and modified to fit the assignment. Original source file is included to view the differences for integrety sake.
 *AI adknowledgement: Code was not generated by AI, but chatGPT was used to assist with conceptual understanding and implementation of interaction between files.
 *All final writing not inlcuded in base code is my own.
 */

#include "Account.h"
#include "Customer.h"
#include <iostream>
#include <string>
using namespace std;





/*
*Below declarations for the menu functions provided by Anderson Wood, reused with permission from the original developer.
*/
void printMenu();
int getMenuOption();
bool isAmountValid(double amount);
bool isMenuChoiceValid(int choice);
void printInvalidMenuChoiceMessage();
double getDepositAmount();
double getWithdrawalAmount();
void printInvalidAmountMessage();

const int DEPOSIT = 1;
const int WITHDRAWAL = 2;
const int CLOSE_OF_BUSINESS = 3;
const int QUIT = 4;

int main()
{
    
    
    
    /*
    *Base code for the menu functions below provided by Anderson Wood, reused with permission from the original developer.
    */
    // just use dummy data for now for the customer and the account
    // we care about interacting with account object for this lab
    Customer customer("0123456789", "customer@cscc.edu");

    // Create savings account object instead of base account to demonstrate polymorphism
    Account* account = new SavingsAccount("5423678409", 100.00, customer, 0.01);

    //Print savingsaccount info and make other objects point to it. 
    account->printAccountInfo();

    int menuChoice = getMenuOption();
    while (menuChoice != QUIT)
    {
        double deposit = 0, withdrawal = 0;

        switch (menuChoice)
        {
        case DEPOSIT:
            deposit = getDepositAmount();
            account->deposit(deposit);
            break;
        case WITHDRAWAL:
            withdrawal = getWithdrawalAmount();
            account->withdraw(withdrawal);
            break;
        case CLOSE_OF_BUSINESS:
            account->closeOfBusiness();
            break;
        }

        menuChoice = getMenuOption();
    }

    // Clean up memory
    delete account;
    return 0;
}

void printMenu()
{
    /* Print account info before menu */

    
    /* Print the main menu options */
    cout << "\nCSCC Bank and Trust" << endl;
    cout << "Select an option:" << endl;
    cout << DEPOSIT << ". Make a deposit" << endl;
    cout << WITHDRAWAL << ". Make a withdrawal" << endl;
    cout << CLOSE_OF_BUSINESS << ". Close of Business" << endl;
    cout << QUIT << ". Quit" << endl;
}

int getMenuOption()
{
    int choice = 0;

    do
    {
        printMenu();
        cin >> choice;

        if (!isMenuChoiceValid(choice))
        {
            printInvalidMenuChoiceMessage();
        }
    } while (!isMenuChoiceValid(choice));

    return choice;
}

bool isMenuChoiceValid(int choice)
{
    return choice >= DEPOSIT and choice <= QUIT;
}

bool isAmountValid(double amount)
{
    return amount > 0;
}

void printInvalidMenuChoiceMessage()
{
    cout << "Invalid option selected. Please try again." << endl;
}

double getDepositAmount()
{
    double deposit = 0;
    do
    {
        cout << "Please enter the deposit amount: $";
        cin >> deposit;

        if (!isAmountValid(deposit))
        {
            printInvalidAmountMessage();
        }

    } while (!isAmountValid(deposit));

    return deposit;
}

double getWithdrawalAmount()
{
    double withdrawal = 0;
    do
    {
        cout << "Please enter the withdrawal amount: $";
        cin >> withdrawal;

        if (!isAmountValid(withdrawal))
        {
            printInvalidAmountMessage();
        }

    } while (!isAmountValid(withdrawal));

    return withdrawal;
}

void printInvalidAmountMessage()
{
    cout << "The dollar amount must be greater than $0.00. Please try again." << endl;
}